name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    # Increase the patch version automatically
    - name: Increase Patch Version
      run: |
        # Assuming version is maintained in a VERSION.txt file
        VERSION=$(cat VERSION.txt)
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
        echo $NEW_VERSION > VERSION.txt
        echo "New version: $NEW_VERSION"

    # Build the jar
    - name: Build with Gradle
      run: ./gradlew build
      
    # Build docker image using multi-stage build
    - name: Build Docker image
      run: |
        docker build --target production -t my-app:$NEW_VERSION .
        
    # Login to Docker Hub (or any other registry)
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    # Push the docker image
    - name: Push Docker image
      run: |
        docker tag my-app:$NEW_VERSION ${{ secrets.DOCKER_USERNAME }}/my-app:$NEW_VERSION
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:$NEW_VERSION
