name: CI/CD Pipeline for Maven Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Increase the patch version automatically (assuming version is in VERSION.txt)
    - name: Increase Patch Version
      run: |
        VERSION=$(cat VERSION.txt)
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
        echo $NEW_VERSION > VERSION.txt
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      shell: bash

    # Build docker image using multi-stage build
    - name: Build Docker image
      run: |
        echo "Building Docker image with tag my-app:$NEW_VERSION"
        docker build -t my-app:$NEW_VERSION .

    # Login to Docker Hub (or any other registry)
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push the docker image
    - name: Push Docker image
      run: |
        docker tag my-app:$NEW_VERSION ${{ secrets.DOCKER_USERNAME }}/my-app:$NEW_VERSION
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:$NEW_VERSION
